### ISSUE TITLE
TypeError in check_for_existing_addon

### ISSUE THREAD

**Issue by tadly** [xbmc/addon-check#147]
Occurred with [this](https://github.com/xbmc/repo-scripts/pull/953) PR.

For searchability here the traceback:
```
The command "if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then kodi-addon-checker --branch=jarvis; fi" exited with 0.

$ if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then kodi-addon-checker --branch=jarvis --PR $(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq); fi
INFO: Checking add-on service.linuxwhatelse.notify
INFO: Created by linuxwhatelse
INFO: Addon id matches folder name
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/kodi-addon-checker", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/kodi_addon_checker/__main__.py", line 89, in main
    report.add(check_artifact(directory, args, args.branch, all_repo_addons, args.PR))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/kodi_addon_checker/__main__.py", line 55, in check_artifact
    return check_addon.start(artifact_path, branch_name, all_repo_addons, pr, config)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/kodi_addon_checker/check_addon.py", line 49, in start
    check_old_addon.check_for_existing_addon(addon_report, addon_path, all_repo_addons, pr)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/kodi_addon_checker/check_old_addon.py", line 31, in check_for_existing_addon
    if addon_name in repo_addons:
TypeError: argument of type 'NoneType' is not iterable
The command "if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then kodi-addon-checker --branch=jarvis --PR $(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq); fi" exited with 1.

Done. Your build exited with 1.
```

**Comment by mzfr** [comment]
This is a bit weird. This will only happen if `repo_addons` will be `None`. And repo_addons shouldn't be `None`.

Did we get this kind of error somewhere else also?

**Comment by mzfr** [comment]
Getting the same error here: https://travis-ci.org/xbmc/addon-check/jobs/466062485

**Comment by LordGameleo** [comment]
@mzfr are you working on this issue?

**Comment by mzfr** [comment]
You can work on this issue of you want

**Comment by LordGameleo** [comment]
@mzfr would you mind briefing me about it.
